spring.application.name=cruddemo
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xepdb1

spring.datasource.username=instructors
spring.datasource.password=instructors
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.main.banner-mode=off
logging.level.root=warn

