spring.application.name=OracleDb
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xepdb1

spring.datasource.username=Student
spring.datasource.password=Student
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.main.banner-mode=off
logging.level.root=warn